### ISSUE TITLE
开启签名校验无法正常发送通知

### ISSUE THREAD

**Issue by xanto521** [721806280/feishu-talk-plugin#17]
在系统配置页面使用不加密方式可以测试发送，使用加密方式测试发送也无法发送。

在Freestyle任务的任务配置的地方不可以用，无论是加密方式还是非加密方式。
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/25278688/224655151-53c72008-6ce9-4c9d-809a-dc6c4812e601.png">

在Pipeline任务内配置脚本可以通知，配置如下，但是和上面一样的位置去配置就无效。只有在pipeline内使用feiShuTalk方法才有效

`pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage('text'){
            steps {
                echo '发送卡片消息...'
            }
            post {
                success {
                    feiShuTalk (
                        robot: 'jenkins-feishu',
                        type: 'INTERACTIVE',
                        title: '📢 Jenkins 构建通知',
                        text: [
                            '📋 **任务名称**：[${JOB_NAME}](${JOB_URL})',
                            '🔢 **任务编号**：[${BUILD_DISPLAY_NAME}](${BUILD_URL})',
                            '🌟 **构建状态**: <font color="green">成功</font>',
                            '🕐 **构建用时**: 2 ms and counting',
                            '👤 **执  行 者**: Started by user anonymous',
                            '<at id=all></at>'
                        ],
                        buttons: [
                           [
                              title: '更改记录',
                              url: '${BUILD_URL}changes'
                           ],
                           [
                              title: '控制台',
                              type: 'danger',
                              url: '${BUILD_URL}console'
                           ]
                        ]
                    )
                }
            }
        }
    }
}
`
环境
jenkins 2.393  docker安装版

**Comment by xanto521** [comment]
还发现一个问题，构建用时变量在echo里可以输出，在feiShuTalk内无法解析出来
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/25278688/224868978-c7e3e8c1-8348-4ba8-bf63-7237a4811892.png">

**Comment by 721806280** [comment]
> 还发现一个问题，构造用时改变量在echo里可以输出，在feiShuTalk里面无法解析出来 <img alt="图像" width="1137" src="https://user-images.githubusercontent.com/25278688/224868978-c7e3e8c1-8348-4ba8-bf63-7237a4811892.png">

文档已经更新，单引号改为双引号即可

**Comment by 721806280** [comment]
测试加密发送BUG已修复
