### ISSUE TITLE
飞书机器人点测试的时候能发出消息，在配置到项目中后就没发消息了

### ISSUE THREAD

**Issue by XiYanXian** [721806280/feishu-talk-plugin#2]

**Comment by 721806280** [comment]
提供下具体步骤信息

**Comment by XiYanXian** [comment]
先是添加了机器人
![image](https://user-images.githubusercontent.com/49447443/206140817-a9410914-4d01-4848-beca-3e26ba0b515c.png)
然后建了个空项目勾选了飞书机器人
![image](https://user-images.githubusercontent.com/49447443/206141064-6ca2af46-6630-44d5-bc41-a6f2627ea822.png)
构建之后的输出
![image](https://user-images.githubusercontent.com/49447443/206141263-d81a3497-1073-40f4-b03a-d175b0f73c71.png)
发不出消息

**Comment by XiYanXian** [comment]
刚开始配置机器人的时候，点测试是能发出测试消息的
![image](https://user-images.githubusercontent.com/49447443/206141840-b372e2f8-8f98-491e-b4f3-5656d5b4c997.png)

**Comment by 721806280** [comment]
测试正常，未复现问题，不确定是不是jenkins版本引起的~ 测试版本:  2.361.1

**Comment by XiYanXian** [comment]
目前使用的jenkins版本是2.380的

**Comment by XiYanXian** [comment]
用了2.375的不行，换成2.361的行了，裂开了

**Comment by zpfhyj** [comment]
我使用最新的jenkins版：2.446的，也是同样的情况。在插件安装页面没问题，但是在项目中没有发送消息。
